### ISSUE TITLE
.listen() is "allowed" on subChannels, but breaks things far far away

### ISSUE THREAD

**Issue by benfleis** [uber/tchannel-node#30]
If .listen() isn't allowed on subChannels, then I suggest that we enforce this policy. Currently it half-works, and causes failures down the road; if I hadn't already gotten help solving it the first time, I would have gone crazy the second time I was upgrading something to new tchannel.

Fail fast would ideal here.

**Comment by Raynos** [comment]
:+1: for fail fast.

**Comment by benfleis** [comment]
I tried the obvious diff, and it breaks tests w/ EADDRINUSE. I haven't had time to track it down, but it's pretty counterintuitive to me. Maybe @jcorbin or @kriskowal will see what I'm missing?

  https://github.com/uber/tchannel-node/compare/wip-subchannel-no-listen

Failure output is in benchmarks:
```
Loading config: /Users/benfleis/src/tchannel/node/.istanbul.yml
running /Users/benfleis/src/tchannel/node/benchmarks/bench_server[31807]

/Users/benfleis/src/tchannel/node/lib/event_emitter.js:140
    throw err;
          ^
TchannelServerListenFailedError: tchannel: listen EADDRINUSE
    at createError (/Users/benfleis/src/tchannel/node/node_modules/error/typed.js:31:22)
    at Object.createError [as TChannelListenError] (/Users/benfleis/src/tchannel/node/node_modules/error/wrapped.js:88:19)
    at TChannel.onServerSocketError (/Users/benfleis/src/tchannel/node/channel.js:498:22)
    at Server.onServerSocketError (/Users/benfleis/src/tchannel/node/channel.js:385:14)
    at Server.emit (events.js:95:17)
    at net.js:1047:12
    at process._tickCallback (node.js:442:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:929:3
child exited /Users/benfleis/src/tchannel/node/benchmarks/bench_server[31807] code 8 signal null
running /Users/benfleis/src/tchannel/node/benchmarks/multi_bench[31808]
1:          PING, 10000/0 min/max/avg/p95:  135/1328/ 707.99/1156.00   1382ms total,  7235.89 ops/sec

/Users/benfleis/src/tchannel/node/lib/event_emitter.js:140
    throw err;
          ^
TchannelServerListenFailedError: tchannel: listen EADDRINUSE
    at createError (/Users/benfleis/src/tchannel/node/node_modules/error/typed.js:31:22)
    at Object.createError [as TChannelListenError] (/Users/benfleis/src/tchannel/node/node_modules/error/wrapped.js:88:19)
    at TChannel.onServerSocketError (/Users/benfleis/src/tchannel/node/channel.js:498:22)
    at Server.onServerSocketError (/Users/benfleis/src/tchannel/node/channel.js:385:14)
    at Server.emit (events.js:95:17)
    at net.js:1047:12
    at process._tickCallback (node.js:442:13)
child exited /Users/benfleis/src/tchannel/node/benchmarks/multi_bench[31808] code 8 signal null
```

**Comment by benfleis** [comment]
Interesting that it succeeds on travis, although makes sense, since I think node uses REUSEPORT always, which behaves differently there. The question still remains: why would moving the .listen() trigger this in the first place?
