### ISSUE TITLE
Cannot read timers of null

### ISSUE THREAD

**Issue by Raynos** [uber/tchannel-node#314]
```
TypeError: Cannot read property 'timers' of null
    at LazyRelayInReq.sendErrorFrame (/var/cache/udeploy/r/hyperbahn/sjc1-produ-0000000136-v1/node_modules/hyperbahn/node_modules/tchannel/lazy_relay.js:456:27)
    at LazyRelayInReq.onError (/var/cache/udeploy/r/hyperbahn/sjc1-produ-0000000136-v1/node_modules/hyperbahn/node_modules/tchannel/lazy_relay.js:439:10)
    at LazyRelayInReq.onTimeout (/var/cache/udeploy/r/hyperbahn/sjc1-produ-0000000136-v1/node_modules/hyperbahn/node_modules/tchannel/lazy_relay.js:267:10)
    at TimeHeap.callExpiredTimeouts (/var/cache/udeploy/r/hyperbahn/sjc1-produ-0000000136-v1/node_modules/hyperbahn/node_modules/tchannel/time_heap.js:211:14)
    at TimeHeap.drainExpired (/var/cache/udeploy/r/hyperbahn/sjc1-produ-0000000136-v1/node_modules/hyperbahn/node_modules/tchannel/time_heap.js:200:14)
    at TimeHeap.onTimeout (/var/cache/udeploy/r/hyperbahn/sjc1-produ-0000000136-v1/node_modules/hyperbahn/node_modules/tchannel/time_heap.js:172:10)
    at onTimeout [as _onTimeout] (/var/cache/udeploy/r/hyperbahn/sjc1-produ-0000000136-v1/node_modules/hyperbahn/node_modules/tchannel/time_heap.js:163:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by Raynos** [comment]
@rf we still have bugs with free() or not free()

**Comment by rf** [comment]
```
TypeError: Cannot read property 'logger' of null
    at LazyRelayInReq.relayRequestlogError [as logError] (/var/cache/udeploy/r/hyperbahn/sjc1-produ-0000000143-v1/node_modules/hyperbahn/node_modules/tchannel/lazy_relay.js:260:23)
    at LazyRelayInReq.onError (/var/cache/udeploy/r/hyperbahn/sjc1-produ-0000000143-v1/node_modules/hyperbahn/node_modules/tchannel/lazy_relay.js:440:10)
    at LazyRelayInReq.onTimeout (/var/cache/udeploy/r/hyperbahn/sjc1-produ-0000000143-v1/node_modules/hyperbahn/node_modules/tchannel/lazy_relay.js:267:10)
    at TimeHeap.callExpiredTimeouts (/var/cache/udeploy/r/hyperbahn/sjc1-produ-0000000143-v1/node_modules/hyperbahn/node_modules/tchannel/time_heap.js:211:14)
    at TimeHeap.drainExpired (/var/cache/udeploy/r/hyperbahn/sjc1-produ-0000000143-v1/node_modules/hyperbahn/node_modules/tchannel/time_heap.js:200:14)
    at TimeHeap.onTimeout (/var/cache/udeploy/r/hyperbahn/sjc1-produ-0000000143-v1/node_modules/hyperbahn/node_modules/tchannel/time_heap.js:172:10)
    at onTimeout [as _onTimeout] (/var/cache/udeploy/r/hyperbahn/sjc1-produ-0000000143-v1/node_modules/hyperbahn/node_modules/tchannel/time_heap.js:163:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```
