### ISSUE TITLE
Exception: Cannot read property socketRemoteAddr of null

### ISSUE THREAD

**Issue by Raynos** [uber/tchannel-node#44]
```
TypeError: Cannot read property 'socketRemoteAddr' of null
    at TChannelInRequest.extendLogInfo (/var/cache/udeploy/r/hyperbahn/sjc1-produ-0000000061-v1/node_modules/hyperbahn/node_modules/tchannel/in_request.js:85:44)
    at ServiceDispatchHandler.rateLimit (/var/cache/udeploy/r/hyperbahn/sjc1-produ-0000000061-v1/node_modules/hyperbahn/service-proxy.js:188:36)
    at ServiceDispatchHandler.handleRequest (/var/cache/udeploy/r/hyperbahn/sjc1-produ-0000000061-v1/node_modules/hyperbahn/service-proxy.js:158:41)
    at TChannelSelfConnection.runHandler (/var/cache/udeploy/r/hyperbahn/sjc1-produ-0000000061-v1/node_modules/hyperbahn/node_modules/tchannel/connection_base.js:207:26)
    at runHandler (/var/cache/udeploy/r/hyperbahn/sjc1-produ-0000000061-v1/node_modules/hyperbahn/node_modules/tchannel/connection_base.js:162:14)
    at process._tickDomainCallback (node.js:463:13)
```

Not quite sure where it comes from. But much sad :(

**Comment by rf** [comment]
This was fixed in d28e5f3cc7d1e00731b9daeff523eb3791b5d3f4
